security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_CATEGORY_SHOW: ROLE_USER
        ROLE_CATEGORY_EDIT: ROLE_CATEGORY_SHOW
        ROLE_ADMIN:       [ROLE_USER, ROLE_PRODUCT_EDIT] #CATEGORY_LIST
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            anonymous: true
            logout: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

    access_control:
        - { path: ^/admin/_css/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
